spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal_project?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
